= Salt mini-Howto =

This Howto is a helpful tool for those who start using Salt and wonder how to tame the beast to produce something fruitful.
At the same time, I am new to AsciiDoc so it is kind of 2-way learning (which never turns out well :-). Good luck!

NOTE: When dealing with linux distribution specific topics, I just describe it the SUSE way, time is short.

== Architecture ==
In Salt-managed environment, there is _one_ salt master and 3 or more salt minions. You enter commands on the master only,
while the minions nicely execute them simultaneously.

== Installation ==
When your nodes' networking is set up correctly and all minions can see the master and the other way round, it's fairly easy.
I will get to this later, I need more practical topics first.

== Basic Command Structure ==
`salt '*' pkg.install boopkg`

Where:

`salt` - Just a salt command, you need to tell the system somehow...

`'\*'` - A target. This way you address the affected minions. '*' means all minions, `'salt4min1'` filters the one.

`pkg.install` - `pkg` is a module name and `install` is one of its function names you want to execute on minions.

`boopkg` - Just an example argument passed to the `install` function.

=== Command Examples ===
----------------------------------------------------------
salt '*' sys.doc # lists all modules and related functions
salt '*' sys.doc pkg # lists all functions of the 'pkg' module
salt '*' sys.doc pkg.install # describes the method
salt '*' cmd.run 'ls -l /etc' # executes the command on the remote shell, try to avoid it as it is not cross-platform
salt 'minion1' grains.ls # lists all grains on a minion (you can add your own to /etc/salt/grains)
----------------------------------------------------------

=== Targetting ===
`'*'` targets _all_ the minions at the same time, but you usually want to target them more specifically.
----------------------------------------------------------
salt 'minion1' disk.usage # targetting a specific single minion by it ID
salt 'minion*' disk.usage # targets matched by globbing
salt -G 'os:Ubuntu' test.ping # target based on information from _Grains_
salt -E 'minion[0-9]' test.ping # target based on a regular expression
salt -L 'minion1,minion2' test.ping # list of multiple tagets
salt -C 'G@os:Ubuntu and minion* or S@192.168.50.*' test.ping # combined query
----------------------------------------------------------

=== Terminology ===
runner::
  ?!><L!KOPJKPO
