= Salt mini-Howto =

== Intro ==
Salt is a framework that can deploy/configure/modify a group of machines to
fulfill tasks defined by their roles.

== Architecture ==
In Salt-managed environment, there is _one_ salt master and 3 or more salt minions. You enter commands on the master only,
while the minions nicely execute them simultaneously.

== Installation ==
When your nodes' networking is set up correctly and all minions can see the
master and the other way round, it's fairly easy.  I will get to this later, I
need more practical topics first.

== Terminology ==
Runners::
 Modules that execute on the Salt master, use to list job status, view events in
 real-time, manage Salt's file server, view Salt mine data etc. Runners are
 called with `salt-run` command line without a target (Salt master is the
 target).
Grain::
 Module that provides data about your minions. Grains include static information
 about the underlying operating system, memory, disks etc. Grains are gathered
 automatically when the minion starts. Grains are an important part of the
 targeting system.
Pillar::
 Pillar delivers data to one or more minions using targeting. The transport is
 encrypted so you can transfer even passwords and ssh keys. Default format for
 storing the pillar data is YAML.
Mine::
 Provides a space for data shared among minions.
State::
 It is a description of a specific profile/role, usually stored in a *.sls
 file for completeness and dependency. Foe example 'web_server' can be a state
 requiring the installation of Apache+MySQL+PHP packages and running their
 services.
State file::
 YAML formatted file (with *.sls extension) that includes Salt commands to define
 a role of one or more targeted machines.

== Basic Command Structure ==
`salt '*' pkg.install boopkg`

Where:

`salt` - Just a salt command, you need to tell the system somehow...

`'\*'` - A target. This way you address the affected minions. '*' means all minions, `'salt4min1'` filters the one.

`pkg.install` - `pkg` is a module name and `install` is one of its function names you want to execute on minions.

`boopkg` - Just an example argument passed to the `install` function.

=== Command Examples ===
----------------------------------------------------------
salt '*' sys.doc # lists all modules and related functions
salt '*' sys.doc pkg # lists all functions of the 'pkg' module
salt '*' sys.doc pkg.install # describes the method
salt '*' cmd.run 'ls -l /etc' # executes the command on the remote shell, try to avoid it as it is not cross-platform
salt 'minion1' grains.ls # lists all grains on a minion (you can add your own to /etc/salt/grains)
----------------------------------------------------------

=== Targetting ===
`'*'` targets _all_ the minions at the same time, but you usually want to target them more specifically.
----------------------------------------------------------
salt 'minion1' disk.usage # targetting a specific single minion by it ID
salt 'minion*' disk.usage # targets matched by globbing
salt -G 'os:Ubuntu' test.ping # target based on information from _Grains_
salt -E 'minion[0-9]' test.ping # target based on a regular expression
salt -L 'minion1,minion2' test.ping # list of multiple tagets
salt -C 'G@os:Ubuntu and minion* or S@192.168.50.*' test.ping # combined query
----------------------------------------------------------

